#     ▄████████     ███    
#    ███    ███ ▀█████████▄
#    ███    ███    ▀███▀▀██
#    ███    ███     ███   ▀
#  ▀███████████     ███    
#    ███    ███     ███    
#    ███    ███     ███    
#    ███    █▀     ▄████▀  
# 
#    Kitty conf 2024   

include ~/.config/kitty/theme/gruvbox.conf

font_family JetBrainsMono Nerd Font Mono
font_size 10
scrollback_lines 2000
wheel_scroll_min_lines 1
initial_window_width 1920 
initial_window_height 1200
window_padding_width 6
cursor_shape block 
shell_integration no-cursor
editor nvim 
allow_hyperlinks yes
confirm_os_window_close 0
enable_audio_bell no
